### PR TITLE
Java: remove unused imports

### LINKED ISSUE #29: java: Remove unused imports
The Java code has many unused imports as remainders from the libsignal-protocol-java import. Find a tool that can detect them.

### PR DESCRIPTION
**Pull request by hiqua**
Closes #29.

Just used IntelliJ IDEA "optimize imports" feature.

### CODE REVIEW

**Comment by jrose-signal** [comment]
Thanks! I'm a bit confused by how it's decided to sort the imports, though: it's not alphabetical (at the top level) and it sometimes uses groups and sometimes doesn't. Are there configuration options we could turn on/off to reduce the amount of reordering?

**Comment by hiqua** [comment]
This is with these settings (defaults I think):

Of course these could be changed.

2021-05-04-213149_1524x543_scrot

**Comment by jrose-signal** [comment]
Ah, great! Going off of what we currently have, I think the preferred groups are something like

- android
- junit
- org.signal.client.internal.Native specifically
- org.signal, org.whispersystems
- java, javax

though it's not super consistent. I'd simplify that to

- org.signal.client.internal.Native specifically
- org.signal, org.whispersystems
- all other packages
- java, javax (it's weird to me that IntelliJ uses the opposite order)

What we'd really like, though, is to add a formatter to Gradle so that these *stay* in order—it doesn't even exactly matter which order, if it's not easily configurable. Do you have any leads on that?

**Comment by hiqua** [comment]
I think @jack-signal already hinted at this there: https://github.com/signalapp/libsignal-client/issues/30

What if you just use the google-java-formatter for all your java code (including the imports)? Then it would be easy to add it to the CI.

**Pull request closed without merging**
